### ISSUE TITLE
Typo in LICENCE file name

### ISSUE THREAD

**Issue by uwu-dev** [sad1stic/sad1stic.github.io#1]
Hey, I think you mistyped **LICENCE.** I'm quite sure, like 96 _coma_ 33 % sure that it is a typo
I've made a pull request with a suggest fix

Code in question:
`LICENCE`

[The file in question](https://github.com/sad1stic/sad1stic.github.io/blob/main/LICENCE)

**Comment by XxB1a** [comment]
![image](https://user-images.githubusercontent.com/73293685/103468734-a70e6300-4d5c-11eb-85d6-8bb8d4be64ce.png)
It isn't a typo, but TY for mentioning it!

**Comment by uwu-dev** [comment]
I actually thought you memed the name
You didn't actually check what I renamed it to in the PR, have you?
